name: Release docker image

on:
  push:
    branches: ['main']

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: install dependencies
        run: npm install

      - name: Release version
        id: release
        uses: codfish/semantic-release-action@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Build the Docker image
        if: steps.release.outputs.new-release-published == 'true'
        run: docker build -t arosicki/devops-ninja:latest -t arosicki/devops-ninja:${{ steps.package-version.outputs.current-version}} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        if: steps.release.outputs.new-release-published == 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        if: steps.release.outputs.new-release-published == 'true'
        run: docker push --all-tags arosicki/devops-ninja
